### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [Croteam-official/Serious-Engine#13]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [stradd](https://github.com/Croteam-official/Serious-Engine/blob/c9fe415f2cddba5ef01c90e0943189b96b0d19b6/Sources/Ecc/Main.cpp#L41)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [ShellPushBuffer](https://github.com/Croteam-official/Serious-Engine/blob/c9fe415f2cddba5ef01c90e0943189b96b0d19b6/Sources/Engine/Base/Shell.cpp#L58)

**Comment by SLAwww** [comment]
This is a good idea, we should have error handling there. The rest of the engine sources use functions from Engine/Base/Memory.h with error handling, but ECC does not link to anything else so it needs separate error handling.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by SLAwww** [comment]
How exactly do you imagine that?

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for your software?

Do you find information sources like the following useful?
* Article "[A Reusable Aspect for Memory Allocation Checking](https://web.archive.org/web/20090808093257/http://research.msrg.utoronto.ca/ACC/Tutorial#A_Reusable_Aspect_for_Memory_All "AspectC Tutorial")"
* Document "[Aspect-Oriented Software Development - An Introduction](https://web.archive.org/web/20130512025224/http://www.info.ucl.ac.be/~jbrichau/courses/introductionToAOSD.pdf "AOSD")" by Johan Brichau and Theo D'Hondt
* Paper "[On Typesafe Aspect Implementations in C++](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.125.2164 "AspectC++")" by Daniel Lohmann and Olaf Spinczyk

**Comment by SLAwww** [comment]
The last link doesn't work for me, and the first two don't really answer my question. Memory allocation functions are already error-checked in the engine, see Engine/Base/Memory.h. What exactly do you propose to change in there and what benefit will it bring?

**Comment by ralight** [comment]
@SLAwww It's possible this is a bot based on other account activity. It looks like @elfring is producing formulaic bug reports based on searches. That's not to ignore some of the points of course.

**Comment by elfring** [comment]
>Memory allocation functions are already error-checked in the engine, …

Are there any functions left over where null pointers will not be handled by the mentioned memory allocation approach?

How do you think about to delegate the source code transformation for more complete exception handling to a development tool like "AspectC++"?
Would you like to reduce efforts for source file maintenance in any ways?

**Comment by SLAwww** [comment]
Please answer my previous question first.

> What exactly do you propose to change in there and what benefit will it bring?

**Comment by elfring** [comment]
* I propose to [handle cross-cutting concerns](https://en.wikipedia.org/wiki/Cross-cutting_concern "Description around cross-cutting concerns") in a more structured way.
* You can benefit from the specification of special source code patterns by automatic code generation, can't you?

**Comment by SLAwww** [comment]
I don't know. You make no clear indication of what you propose. But feel free to try coding that into Serious Engine and we'll see if it really brings any benefit.

**Comment by elfring** [comment]
Would you like to look a bit more at possibilities around the combination of pointcuts and advices into reusable aspect specifications?

**Comment by SLAwww** [comment]
No thanks, if that wouldn't be too hard I'd like to see how exactly your proposition will affect Serious Engine code.

**Comment by elfring** [comment]
Do you get further ideas from the following example for a small AspectC++ script?
```
…
aspect string_duplication_check
{
 advice execution("% * strdup(...)"): after()
 {
  if (*tjp->result() == NULL)
     abort();
 }
};
…
```

**Comment by SLAwww** [comment]
It seems more complicated than already existing AllocateMemory function that does just that error check. I don't understand why you think it is better.

**Comment by elfring** [comment]
* Does the function "strdup" get the needed memory from the mentioned customised allocation approach?
* Is the aspect specification easily extensible for more use cases?

**Comment by SLAwww** [comment]
I'm sorry, but this conversation doesn't seem to be constructive. You initially made a good point, but then didn't propose a concrete and useful code modification. As I said, you are free to try whatever you wish, maybe you were right after all. If you manage to implement aspect-oriented approach in Serious-Engine, that's great, I'd love to see that in action. But until then I'll have to close this discussion.

**Comment by elfring** [comment]
Would you like to care for the failure possibility of [a function like "fprintf"](https://github.com/Croteam-official/Serious-Engine/blob/c9fe415f2cddba5ef01c90e0943189b96b0d19b6/Sources/Engine/Base/Console.cpp#L207 "Update candidate: CConsole::PutString()")?
