### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by Krakean** [Croteam-official/Serious-Engine#15]
Hello.
Just downloaded sources from master, opened All.sln, and when I trying to build Debug conf. under VS2015 (Update 2 RC, if it matters) I got this:
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'Engine/Classes/BaseEvents.h': No such file or directory	Depend	D:\aGIT\GameEngines\SERIOUS ENGINE\Sources\Engine\Entities\Entity.h	56	
Error	C1083	Cannot open include file: 'Engine/Classes/BaseEvents.h': No such file or directory	Shaders	D:\aGIT\GameEngines\SERIOUS ENGINE\Sources\Engine\Entities\Entity.h	56	
Error	C1083	Cannot open include file: 'Engine/Classes/BaseEvents.h': No such file or directory	DecodeReport	D:\aGIT\GameEngines\SERIOUS ENGINE\Sources\Engine\Entities\Entity.h	56	

I didn't found "BaseEvents.h" file, only "BaseEvents.es".

Is there something I do wrong?

**Comment by SLAwww** [comment]
Avoid spaces in the path and make the path shorter. These issues are mentioned in the README.

**Comment by DaveMeowintons** [comment]
I have no spaces within the path and the path is as short as I can make it - cannot find BaseEvents.h

**Comment by SLAwww** [comment]
Can I see your build log?

**Comment by DaveMeowintons** [comment]
Output log:
[Serious_Engine_Output.txt](https://github.com/Croteam-official/Serious-Engine/files/172970/Serious_Engine_Output.txt)

Looking in Engine\Classes ends up showing BaseEvents.es and BaseEvents.h_tmp but no signs of BaseEvents.h

**Comment by Krakean** [comment]
[b]DaveMeowintons[/b]
>3>  Engine/Classes/PlayerEntity.es
>3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code -1073740791.

Let me assume.
Try following: look for Ecc.exe in Bin\, Run it manually. Do you get an error like "ucrtbased.dll not found"? If you do, go to your Windows Kits folder, look for this dll there, and copy it to Bin\Debug or Bin\ folder. Should help.

**Comment by SLAwww** [comment]
Your solution path is still way too long. Shorten it down, and try not to keep it on the desktop.

**Comment by DaveMeowintons** [comment]
Ecc.exe won't run for now which may or may not be due to lack of files.

I moved the 'Serious-Engine-master' into c:\ which has fixed the BaseEvents.h not showing up, however has now caused MovableModelEntity.h and MovableBrushEntity.h disappear somewhere - perhaps they were never created in the first place. Building the engine elsewhere doesn't create them, instead I get the .h_tmp file.
 
[Serious_Engine_Output2.txt](https://github.com/Croteam-official/Serious-Engine/files/174337/Serious_Engine_Output2.txt)

**Comment by SLAwww** [comment]
Try using the release version of ECC. Just build it in Release, then copy to Bin/Debug replacing the debug one, and see if that helps building Engine and EntitiesMP.

**Comment by vroach** [comment]
@SLAwww or just rename the folder in "Engine" to "Classes"? because I think my build had it like "Entity Classes" or something

**Comment by DaveMeowintons** [comment]
Copying release version over into bebug has worked; no errors in building solution.

Thank you for your help!
