### ISSUE TITLE
fatal error C1083: Cannot open include file: 'Engine/Classes/BaseEvents.h': No such file or directory

### ISSUE THREAD

**Issue by Neknail** [Croteam-official/Serious-Engine#21]
When I built the solution with VS Enterprise 2015 , error in the subject was found. 
The original solution and project are targeted on VS 2013, I have to upgrade them to target on VS 2015 by right-clicking the solution and selecting the "Retarget solution" command.

Anything I missed? 

Thanks

**Comment by SLAwww** [comment]
Build log please?

**Comment by Neknail** [comment]
>  StdAfx.cpp
13>C:\Users\klian\Source\Repos\Serious-Engine\Sources\Engine/Entities/Entity.h(56): fatal error C1083: Cannot open include file: 'Engine/Classes/BaseEvents.h': No such file or directory
14> 
@SLAwww Thanks!

**Comment by SLAwww** [comment]
Your solution path is way too long. Shorten it down and try again.
This happens so often I'm going to add this to readme.

**Comment by Neknail** [comment]
Thanks, it works now.

2016-03-16 17:12 GMT+08:00 SLAwww <notifications@github.com>:
