### ISSUE TITLE
How use GRO file?

### ISSUE THREAD

**Issue by Sesilla** [Croteam-official/Serious-Engine#24]
Hello,
I have compiled the source code, when I run it I get an error when loading a level of .wld (which does not exist).

Have you any tips about it?

Thank you, Regards
Sesilla

**Comment by yamgent** [comment]
Did you copy all of the game's .gro files from Steam into your repository directory? The default .gro file provided in the repository do not contain any levels.

**Comment by SLAwww** [comment]
What exactly do you run, an editor or a game itself? May I see the log file for whatever application you run?

**Comment by Sesilla** [comment]
I have copied the files .gro from my old copy Serious Sam The Second Encounter (aka Serious Sam 2 right?) in the "Serious-Engine-master". Executing SeriousSam.exe this log:

`--- Serious Engine Startup ---
  SeriousEngine Build: 10000.10

Executable: E:\Serious-Engine-master\Bin\SeriousSam.exe
Assumed engine directory: E:\Serious-Engine-master\

Examining underlying OS...
  Type: WinNT
  Version: 6.1, build 7601
  Misc: Service Pack 1

Detecting CPU...
  Vendor: AuthenticAMD
  Type: 0, Family: 15, Model: 1, Stepping: 2
  MMX : Yes
  CMOV: Yes
  Clock: 3800MHz

Global memory status...
  Physical memory used:    0/4095MB
  Page file used:          0/4095MB
  Virtual memory used:    66/2047MB
  Memory load:  15%
  Process working set: 0MB-1MB

Cannot load variable from 'DefaultMod.txt':
Cannot open file `E:\Serious-Engine-master\DefaultMod.txt' (No such file or directory) ()
Current mod: <none>
Loading group files...
  E:\Serious-Engine-master\Patch_02_066_Content_ITL.gro: 1 files
  E:\Serious-Engine-master\Movies_PC_02.gro: 44 files
  E:\Serious-Engine-master\Movies_PC_01.gro: 52 files
  E:\Serious-Engine-master\Content_ITL.gro: 213 files
  E:\Serious-Engine-master\All_PC_03.gro: 3274 files
  E:\Serious-Engine-master\All_PC_02.gro: 5213 files
  E:\Serious-Engine-master\All_PC_01.gro: 1194 files

Detecting input devices...
  joysticks found: 16
  joysticks allowed: 8
  joy 1:  error 0x000000a5
  joy 2:  error 0x000000a5
  joy 3:  error 0x000000a5
  joy 4:  error 0x000000a5
  joy 5:  error 0x000000a5
  joy 6:  error 0x000000a5
  joy 7:  error 0x000000a5
  joy 8:  error 0x000000a5

Desktop settings...
  Color Depth: 32bit
  Screen: 1920x1080
  Virtual screen: 1920x1080
  Monitors directly reported: 1

Current display: 'c' version 1025 - 1920x1080x32

Initializing sound...
OGG playing disabled: Cannot load vorbisfile.dll.
MPX playing disabled: Cannot load amp11lib.dll.
  Detected devices: 3
    device 0: A
      ver: 1537, id: 1.100
      form: 0x000fffff, ch: 2, support: 0x0000002c
    device 1: R
      ver: 1537, id: 1.100
      form: 0x000fffff, ch: 2, support: 0x0000002c
    device 2: R
      ver: 1537, id: 1.100
      form: 0x000fffff, ch: 2, support: 0x0000002c

  CDS: mode reset to original desktop settings
FatalError:
Cannot initialize classes:
Cannot open file `E:\Serious-Engine-master\Classes\Player.ecl' (No such file or directory) ()`

**Comment by SLAwww** [comment]
First of all, Serious Sam 2 and Serious Sam: The Second Encounter are different games. You need GRO files from The Second Encounter (the ones from The First Encounter will also work). Second, an error explicitly tells you that file 'E:\Serious-Engine-master\Classes\Player.ecl' is missing. It is originally located in SE1_10.gro, which is supplied with the engine sources. It seems that you deleted SE1_10.gro, but it is a required file.

**Comment by Sesilla** [comment]
Thanks SLAwww, my mistake about Serious Sam 2 and Serious Sam: The Second Encounter. Ok for the SE1_10.gro, i deleted it.

**Comment by nemo22** [comment]
I know this is closed, bud i still can't start any map in engine. I try to copy gro files from SSHD First Encouter, also from Second Encouter, but no luck. In log it looks like files are loaded but i can't run any map  nor see any in menu. And as i konw, there is no console command in Serious Sam to load map/wolrd file.

**Comment by SLAwww** [comment]
SSHD First Encounter/Second Encounter are different games on a different engine. You need the classic First Encounter/Second Encounter, no the HD version.

**Comment by nemo22** [comment]
Aha, ok. That'a a bit problem :-(. Now i read again read.me and in running part is the mentioned SS Classic. It may bee good idea to highlight that.
Thanks anyway.

**Comment by Siam63** [comment]
> First of all, Serious Sam 2 and Serious Sam: The Second Encounter are different games. You need GRO files from The Second Encounter (the ones from The First Encounter will also work). Second, an error explicitly tells you that file 'E:\Serious-Engine-master\Classes\Player.ecl' is missing. It is originally located in SE1_10.gro, which is supplied with the engine sources. It seems that you deleted SE1_10.gro, but it is a required file.

I have the SE1_10.gro file but inside of my: ~/Library/Application Support/Serious Engine/serioussamfe directory, it says: 

Cannot initialize classes: Expected keyword Package: not found

Do you have any idea how to resolve this?
