### ISSUE TITLE
Why was OGG support removed?

### ISSUE THREAD

**Issue by Danfun64** [Croteam-official/Serious-Engine#36]
Anyone who prefers OGG over MP3 for philosphical reasons is getting thrown under the bus here. Can you explain why OOG support was removed?

**Comment by fenollp** [comment]
what are you talking about https://github.com/Croteam-official/Serious-Engine/pull/35

**Comment by SLAwww** [comment]
OGG support was in fact **returned** by the latest commits. It is no longer "removed".
