### ISSUE TITLE
High-res logo?

### ISSUE THREAD

**Issue by rcgordon** [Croteam-official/Serious-Engine#39]
Is there a high-resolution copy of the Serious Sam logo laying around Croteam's offices that we can put in revision control? There's already Sources/SeriousSam/Splash.bmp, at 256x256 pixels, but modern machines can use 512x512 just for the game's icon.  :)

**Comment by zcaliptium** [comment]
Hi Ryan! Maybe use image from Google images? http://www.warinccommunity.com/2013//images/immagininews/serious_sam_logo.png

**Comment by SLAwww** [comment]
This one is by Croteam.
![seriousbomb](https://cloud.githubusercontent.com/assets/17743522/14403720/d3741da4-fe6a-11e5-91f9-884f11837df9.png)

**Comment by rcgordon** [comment]
Thanks!
