### ISSUE TITLE
GPL headers absent

### ISSUE THREAD

**Issue by leilei-** [Croteam-official/Serious-Engine#4]
It seems so unusual to open a source file of a GPLv2 engine to see there's still a "(C) 2002-2012 Croteam All Rights reserved" instead of the usual GPL header block.

Also is this GPLv2 or GPLv2+?  The latter allows GPLv3 use, as well as being more legally compatible (such as those earlier id software engine GPLv2+ releases)

**Comment by SLAwww** [comment]
This commit https://github.com/Croteam-official/Serious-Engine/commit/c9fe415f2cddba5ef01c90e0943189b96b0d19b6 adds GPL headers to files. If you find any more files that require GPL headers, please let me know.
A LICENSE file explicitly states that the license is GPLv2.

**Comment by leilei-** [comment]
Cool; thanks for the clarification!
