### ISSUE TITLE
never mind

### ISSUE THREAD

**Issue by leilei-** [Croteam-official/Serious-Engine#6]
never mind

**Comment by SLAwww** [comment]
Bump mapping was scrapped from the release version of the game. Perhaps @alenl might have a backup of the engine code with bump mapping still included.

**Comment by leilei-** [comment]
It was in 1.04 at the latest (Sep 2001) and gone by 1.05 at least

**Comment by rcgordon** [comment]
I have what I think are the 1.04 sources, but I'm pretty sure this code still exists in the latest. It's called "detail mapping" in the renderer, I think:

https://github.com/Croteam-official/Serious-Engine/blob/master/Sources/Engine/Models/RenderModel_View.cpp#L2243

I could be wrong, though!

**Comment by leilei-** [comment]
Nah, detail mapping is something else. I'm referring to this effect seen only in pre-1.05 TFE versions.  You'll find a bumpmapping teapot in the Temple of Models in the First Encounter technology test map.

The Second Encounter changed the bumpmapping teapot to a detailmapping teapot however.

**Comment by DanielGibson** [comment]
the same scene in motion: https://youtu.be/mOeKMcFZ6MM?t=689

**Comment by leilei-** [comment]
given the direction this repo is going, this seems unlikely

**Comment by rcgordon** [comment]
You can close this, but I was going to poke around my original sources more when I had a moment. Consider reopening for now, in case it pans out?

**Comment by leilei-** [comment]
Maybe for a branch in a fork... but as far as this repository goes, official engine bumpmaps are dead to me.

**Comment by SLAwww** [comment]
Your comment was deleted because it contained only destructive criticism. Menu system refactoring really had to be done, and nothing else in the engine is a subject for such massive refactoring, at least not in the main branch.

**Comment by alenl** [comment]
Sorry for the delay guys, my time's been spread thin lately. Anyway
