### ISSUE TITLE
Generated files

### ISSUE THREAD

**Issue by LeonardKoenig** [Croteam-official/Serious-Engine#9]
This is just a listing of all generated files I stumble[d] across (in Sources/ subdir):
 - `Ecc/Scanner.cpp`
 - `Engine/Ska/smcPars.cpp`
 - `Engine/Base/Scanner.cpp`
 - `Engine/Ska/smcScan.cpp`
 - `SeriousSkaStudio/Scanner.cpp`
 - `WorldEditor/hlp/resources.hm`

these can be safely removed.

Possibly one should also add the Configuration files to the .gitignore

**Comment by SLAwww** [comment]
There are much more generated files. Every .ES file is compiled using ECC.exe into one .CPP and two .H files. I'll try to exclude those.

**Comment by LeonardKoenig** [comment]
Yes but these are not included in the repo here. I'm currently tracking them down and eventually do a pull request (with .gitignore update)
